---
# tasks file for disks_settings

  - name: Creates temp directory
    file:
      path: "{{ temp_dir }}"
      state: directory

  - name: Copy start_resize_bash to resize image cow2
    template:
      src: start_resize_bash
      dest: "{{ temp_dir }}/start_resize_bash"
      mode: +x

  - name: Execute a bash script
    command: "{{ temp_dir }}/start_resize_bash"
    args:
      chdir: "{{ temp_dir }}"

  - name: Delete temp directory
    file:
      path: "{{ temp_dir }}"
      state: absent

  - name: create directory for mounting 14T
    file:
      path: "{{ mnt_dir_14t }}"
      state: directory

  - name: Automount 14T disk by UUID
    ansible.posix.mount:
      path: "{{ mnt_dir_14t }}"
      src: "{{ mnt_name_in_terraform_14t }}"
      opts: "trans=virtio,version=9p2000.L,rwx"
      fstype: 9p
      state: mounted

