---
# tasks file for system_settings

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install systems packages
    apt: 
      pkg: "{{ packagesSystem }}"

  - name: add zshrc for root
    copy:
      src: zshrc
      dest: /root/.zshrc
      mode: +x

  - name: change user shell to zsh
    user:
      name: "{{ user }}" 
      shell: /usr/bin/zsh


