---
# tasks file for install_docker

  - name: Add an Apt signing key to a specific keyring file
    ansible.builtin.apt_key:
      id: 7EA0A9C3F273FCD8 
      url: https://download.docker.com/linux/debian/gpg
      keyring: /etc/apt/trusted.gpg.d/debian.gpg

  - name: somerepo | apt source
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install docker packages
    apt:
      pkg: "{{ packagesDocker }}"

  - name: Add the user root with a bash shell, appending the group docker
    ansible.builtin.user:
      name: "{{ user }}"
      shell: /bin/bash
      groups: docker
      append: yes

  - name: Stop service docker, if running and Enable service docker
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: true

